### ISSUE TITLE
"Standard" go install support

### ISSUE THREAD

**Issue by farzadmf** [pallavJha/chaakoo#4]
Hi,

Found your tool through your post on Reddit, thank you, and it's a very promising tool.

However, one thing that IMO is lacking is the support to install the binary the standard way (`go install ...@latest` for `go 1.16+`). If you want, you can also support the _old_ way of doing `go get ...`.

This for me personally is a blocker because `go install` is the way I use to install plugins, without the hastle of searching Github for the latest release, download, `chmod`, copy to `PATH`, etc.

Of course, just a friendly suggestion :slightly_smiling_face:

**Comment by farzadmf** [comment]
Nice @pallavJha , thank you for the quick reply

**Comment by anishmansuri** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Charming-ai, @kierandrewett, @harryEth, @FFBOND, @ykl124, @albovieira, @samyzhh, @youcanstewit, @kondratovbr, @Kaonashi913, @mikyR, @stdafx-h, @xiaozhiliaoo, @yiyi-zhang-cu, @kalinstoilov, @Licoricewo, @johai, @scientistnik, @kaiwolfram, @stevenling, @sjbr, @AnandShastry, @rayspock, @fbaiesec, @northeastfinest01, @mcarrier69, @bsdaddict, @Deviluna, @linux2017, @bookug, @hubertwng, @migueldbmartins, @jeevanpillay, @bony2023, @rigomortiz, @whiteyhat, @kungenw4301, @fxplayer, @MartinRdw, @svrnhdl, @tsteinholz, @Gilbert-Changky, @qingyunwhu, @XuJiandong, @nomanbd, @mrdede, @philwantsfish, @designated-compiler, @aooyi, @NotStatilkodmsod, @Jwkozicz, @kalinstoilov, @BarisJKC, @icindy, @bcho, @wangdeshui, @dbaspider, @wisteken, @lemonnight, @justicelee, @sauravs, @drm999ac, @yanminhui, @DanielReidme, @cuzox-sf, @GABOSNAKE, @micxael, @lipengxiangEdward, @rsaLive, @skyzhou, @TZJ1997, @mengsuiqingming, @yuanzhengxiong, @lightmyfire17, @liamengland1, @jeffpalmeri, @gireeshp, @krasotkina93, @donchanee, @iamjinlei, @matthewkeil, @CongLeSolutionX, @slmjkdbtl, @HachemiH, @FashionSuperman, @catteforry, @Braw115, @greenboxal, @songsin, @IvanCampos, @Achint08, @henryperson, @weijihao, @qingyouzhao, @chenyu1990, @bytefly, @eason5568, @deeperlearner, @youcanstewit
